name: Releases

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  linux:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          submodules: 'recursive'

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Install Rust Toolchain
        run: rustup update && rustup target add armv7-linux-androideabi aarch64-linux-android i686-linux-android x86_64-linux-android

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./app/src/main/rust"

      - name: CMake Cache
        uses: actions/cache@v3
        with:
          path: |
            app/.cxx
            app/src/main/cpp/nettle/nettle
          key: ${{ runner.os }}-cmake-${{ hashFiles('gradle/libs.versions.toml', 'app/build.gradle.kts', 'app/src/main/cpp/CMakeLists.txt') }}
          restore-keys: ${{ runner.os }}-cmake-

      - name: Gradle Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleRelease

      - name: Rename Apks
        run: |
          mv app/build/outputs/apk/defaultGms/release/app-default-gms-universal-release.apk EhViewer-${{ github.ref_name }}-default-universal.apk
          mv app/build/outputs/apk/defaultGms/release/app-default-gms-arm64-v8a-release.apk EhViewer-${{ github.ref_name }}-default-arm64-v8a.apk
          mv app/build/outputs/apk/defaultGms/release/app-default-gms-x86_64-release.apk EhViewer-${{ github.ref_name }}-default-x86_64.apk
          mv app/build/outputs/apk/defaultGms/release/app-default-gms-x86-release.apk EhViewer-${{ github.ref_name }}-default-x86.apk
          mv app/build/outputs/apk/defaultGms/release/app-default-gms-armeabi-v7a-release.apk EhViewer-${{ github.ref_name }}-default-armeabi-v7a.apk
          mv app/build/outputs/mapping/defaultGmsRelease/mapping.txt EhViewer-${{ github.ref_name }}-default-mapping.txt
          mv app/build/outputs/native-debug-symbols/defaultGmsRelease/native-debug-symbols.zip EhViewer-${{ github.ref_name }}-default-native-debug-symbols.zip

          mv app/build/outputs/apk/marshmallowGms/release/app-marshmallow-gms-universal-release.apk EhViewer-${{ github.ref_name }}-marshmallow-universal.apk
          mv app/build/outputs/apk/marshmallowGms/release/app-marshmallow-gms-arm64-v8a-release.apk EhViewer-${{ github.ref_name }}-marshmallow-arm64-v8a.apk
          mv app/build/outputs/apk/marshmallowGms/release/app-marshmallow-gms-x86_64-release.apk EhViewer-${{ github.ref_name }}-marshmallow-x86_64.apk
          mv app/build/outputs/apk/marshmallowGms/release/app-marshmallow-gms-x86-release.apk EhViewer-${{ github.ref_name }}-marshmallow-x86.apk
          mv app/build/outputs/apk/marshmallowGms/release/app-marshmallow-gms-armeabi-v7a-release.apk EhViewer-${{ github.ref_name }}-marshmallow-armeabi-v7a.apk
          mv app/build/outputs/mapping/marshmallowGmsRelease/mapping.txt EhViewer-${{ github.ref_name }}-marshmallow-mapping.txt
          mv app/build/outputs/native-debug-symbols/marshmallowGmsRelease/native-debug-symbols.zip EhViewer-${{ github.ref_name }}-marshmallow-native-debug-symbols.zip

      - name: Releases
        uses: softprops/action-gh-release@v1
        with:
          body: Bump Version
          files: |
            EhViewer-${{ github.ref_name }}-default-universal.apk
            EhViewer-${{ github.ref_name }}-default-arm64-v8a.apk
            EhViewer-${{ github.ref_name }}-default-x86_64.apk
            EhViewer-${{ github.ref_name }}-default-x86.apk
            EhViewer-${{ github.ref_name }}-default-armeabi-v7a.apk
            EhViewer-${{ github.ref_name }}-default-mapping.txt
            EhViewer-${{ github.ref_name }}-default-native-debug-symbols.zip

            EhViewer-${{ github.ref_name }}-marshmallow-universal.apk
            EhViewer-${{ github.ref_name }}-marshmallow-arm64-v8a.apk
            EhViewer-${{ github.ref_name }}-marshmallow-x86_64.apk
            EhViewer-${{ github.ref_name }}-marshmallow-x86.apk
            EhViewer-${{ github.ref_name }}-marshmallow-armeabi-v7a.apk
            EhViewer-${{ github.ref_name }}-marshmallow-mapping.txt
            EhViewer-${{ github.ref_name }}-marshmallow-native-debug-symbols.zip
